class MainnRunner
{
	public static void main(String[] values)
	{
		System.out.println("Festival details:");
		String name="Diwali";
		String date="27th Octuber";
		String day="Monday";
		Festival festival1 = new Festival(name,date,day);
		System.out.println("Festival Name: "+festival1.name);
		System.out.println("Festival Date: "+festival1.date);
		System.out.println("Festival Day: "+festival1.day);
		
		String name1="Gowri Ganesha Chaturthi";
		String date1="25th September";
		String day1="Tuesday";
		Festival festival2 = new Festival(name1,date1,day1);
		System.out.println();
		System.out.println("Festival Name: "+festival2.name);
		System.out.println("Festival Date: "+festival2.date);
		System.out.println("Festival Day: "+festival2.day);
		
		String name2="Holi";
		String date2="14th March";
		String day2="Friday";
		Festival festival3 = new Festival(name2,date2,day2);
		System.out.println();
		System.out.println("Festival Name: "+festival3.name);
		System.out.println("Festival Date: "+festival3.date);
		System.out.println("Festival Day: "+festival3.day);
		
		String name3="Ramzan";
		String date3="31st March";
		String day3="Monday";
		Festival festival4 = new Festival(name3,date3,day3);
		System.out.println();
		System.out.println("Festival Name: "+festival4.name);
		System.out.println("Festival Date: "+festival4.date);
		System.out.println("Festival Day: "+festival4.day);
		
		String name4="Yogadi";
		String date4="30th March";
		String day4="Sunday";
		Festival festival5 = new Festival(name4,date4,day4);
		System.out.println();
		System.out.println("Festival Name: "+festival5.name);
		System.out.println("Festival Date: "+festival5.date);
		System.out.println("Festival Day: "+festival5.day);
		
		System.out.println("\\\\End////");
		
		System.out.println();
		
		System.out.println("Chat List...");
		int number1=1000;
		String type1="Personal Chat";
		String location1="Whatsapp";
		Chat chat1 = new Chat(number1,type1,location1);
		System.out.println("Number of chat: "+chat1.number);
		System.out.println("Types of Chats: "+chat1.type);
		System.out.println("Chat Location: "+chat1.location);
		System.out.println();
		int number2=1560;
		String type2="Group Chat";
		String location2="Instagram";
		Chat chat2 = new Chat(number2,type2,location2);
		System.out.println("Number of chat: "+chat2.number);
		System.out.println("Types of Chats: "+chat2.type);
		System.out.println("Chat Location: "+chat2.location);
		System.out.println();
		int number3=5460;
		String type3="Text Message";
		String location3="SMS";
		Chat chat3 = new Chat(number3,type3,location3);
		System.out.println("Number of chat: "+chat3.number);
		System.out.println("Types of Chats: "+chat3.type);
		System.out.println("Chat Location: "+chat3.location);
		System.out.println();
		int number4=60;
		String type4="Greating Chat";
		String location4="Facebook";
		Chat chat4 = new Chat(number4,type4,location4);
		System.out.println("Number of chat: "+chat4.number);
		System.out.println("Types of Chats: "+chat4.type);
		System.out.println("Chat Location: "+chat4.location);
		System.out.println();
		int number5=40;
		String type5="Well Come";
		String location5="Snapchart";
		Chat chat5 = new Chat(number5,type5,location5);
		System.out.println("Number of chat: "+chat5.number);
		System.out.println("Types of Chats: "+chat5.type);
		System.out.println("Chat Location: "+chat5.location);
		System.out.println();
		System.out.println("<<<Finish>>>");
		
		System.out.println();
		System.out.println("-------Harpic List------");
		int volume1=1;
		String flavor1="Jasmin";
		int price1=99;
		Harpic harpic1 = new Harpic(volume1,flavor1,price1);
		System.out.println("Harpic Volume: "+harpic1.volume+"kg");
		System.out.println("Harpic flavor: "+harpic1.flavor);
		System.out.println("Harpic Price: "+harpic1.price);
		System.out.println();
		int volume2=7;
		String flavor2="Rose";
		int price2=909;
		Harpic harpic2 = new Harpic(volume2,flavor2,price2);
		System.out.println("Harpic Volume: "+harpic2.volume+"kg");
		System.out.println("Harpic flavor: "+harpic2.flavor);
		System.out.println("Harpic Price: "+harpic2.price);
		System.out.println();
		int volume3=5;
		String flavor3="Strawberry";
		int price3=570;
		Harpic harpic3 = new Harpic(volume3,flavor3,price3);
		System.out.println("Harpic Volume: "+harpic3.volume+"kg");
		System.out.println("Harpic flavor: "+harpic3.flavor);
		System.out.println("Harpic Price: "+harpic3.price);
		System.out.println();
		int volume4=40;
		String flavor4="Modicare";
		int price4=1099;
		Harpic harpic4 = new Harpic(volume4,flavor4,price4);
		System.out.println("Harpic Volume: "+harpic4.volume+"kg");
		System.out.println("Harpic flavor: "+harpic4.flavor);
		System.out.println("Harpic Price: "+harpic4.price);
		System.out.println();
		int volume5=10;
		String flavor5="Vestige";
		int price5=199;
		Harpic harpic5 = new Harpic(volume5,flavor5,price5);
		System.out.println("Harpic Volume: "+harpic5.volume+"kg");
		System.out.println("Harpic flavor: "+harpic5.flavor);
		System.out.println("Harpic Price: "+harpic5.price);
		System.out.println();
		System.out.println(":::END:::");
		System.out.println();
		
		System.out.println(":::Charger List:::");
		String chargerType1="C-type";
		int voltage1=200;
		String company1="SAMSONG";
		Charger charger1 = new Charger(chargerType1,voltage1,company1);
		System.out.println("Type Of Charger: "+charger1.type);
		System.out.println("Voltage Capacity: "+charger1.voltage+"mh");
		System.out.println("Charger Company: "+charger1.company);
		System.out.println();
		String chargerType2="B-type";
		int voltage2=100;
		String company2="Intel";
		Charger charger2 = new Charger(chargerType2,voltage2,company2);
		System.out.println("Type Of Charger: "+charger2.type);
		System.out.println("Voltage Capacity: "+charger2.voltage+"mh");
		System.out.println("Charger Company: "+charger2.company);
		System.out.println();
		String chargerType3="A-type";
		int voltage3=20;
		String company3="Nokio";
		Charger charger3 = new Charger(chargerType3,voltage3,company3);
		System.out.println("Type Of Charger: "+charger3.type);
		System.out.println("Voltage Capacity: "+charger3.voltage+"mh");
		System.out.println("Charger Company: "+charger3.company);
		System.out.println();
		String chargerType4="Small Pin";
		int voltage4=10;
		String company4="Nokio C1";
		Charger charger4 = new Charger(chargerType4,voltage4,company4);
		System.out.println("Type Of Charger: "+charger4.type);
		System.out.println("Voltage Capacity: "+charger4.voltage+"mh");
		System.out.println("Charger Company: "+charger4.company);
		System.out.println();
		String chargerType5="Large Pin";
		int voltage5=15;
		String company5="Karbon";
		Charger charger5 = new Charger(chargerType5,voltage5,company5);
		System.out.println("Type Of Charger: "+charger5.type);
		System.out.println("Voltage Capacity: "+charger5.voltage+"mh");
		System.out.println("Charger Company: "+charger5.company);
		System.out.println();
		System.out.println("^^^^END^^^^");
		System.out.println();
		System.out.println("@@@WhatsApp List@@@");
		boolean login1=true;
		boolean logout1=false;
		int timeSpend1=4;
		WhatsApp whatsApp1 = new WhatsApp(login1,logout1,timeSpend1);
		System.out.println("WhatsApp Login: "+whatsApp1.login);
		System.out.println("WhatsApp Logout: "+whatsApp1.logout);
		System.out.println("Total Time Spend: "+whatsApp1.timeSpend+"hours");
		System.out.println();
		boolean login2=false;
		boolean logout2=true;
		int timeSpend2=0;
		WhatsApp whatsApp2 = new WhatsApp(login2,logout2,timeSpend2);
		System.out.println("WhatsApp Login: "+whatsApp2.login);
		System.out.println("WhatsApp Logout: "+whatsApp2.logout);
		System.out.println("Total Time Spend: "+whatsApp2.timeSpend+"hours");
		System.out.println();
		boolean login3=false;
		boolean logout3=true;
		int timeSpend3=24;
		WhatsApp whatsApp3 = new WhatsApp(login3,logout3,timeSpend3);
		System.out.println("WhatsApp Login: "+whatsApp3.login);
		System.out.println("WhatsApp Logout: "+whatsApp3.logout);
		System.out.println("Total Time Spend: "+whatsApp3.timeSpend+"hours");
		System.out.println();
		boolean login4=true;
		boolean logout4=true;
		int timeSpend4=10;
		WhatsApp whatsApp4 = new WhatsApp(login4,logout4,timeSpend4);
		System.out.println("WhatsApp Login: "+whatsApp4.login);
		System.out.println("WhatsApp Logout: "+whatsApp4.logout);
		System.out.println("Total Time Spend: "+whatsApp4.timeSpend+"hours");
		System.out.println();
		boolean login5=false;
		boolean logout5=false;
		int timeSpend5=05;
		WhatsApp whatsApp5 = new WhatsApp(login5,logout5,timeSpend5);
		System.out.println("WhatsApp Login: "+whatsApp5.login);
		System.out.println("WhatsApp Logout: "+whatsApp5.logout);
		System.out.println("Total Time Spend: "+whatsApp5.timeSpend+"hours");
		System.out.println();
		System.out.println("[List Of Rat poison]");
		String ratPoisonType1="Bromethalin";
		boolean strong1=true;
		int required1=1;
		RatPoison ratpoison1 = new RatPoison(ratPoisonType1,strong1,required1);
		System.out.println("Type of Rat Poison: "+ratpoison1.ratPoisonType);
		System.out.println("Strongness :"+ratpoison1.strong);
		System.out.println("Reqired: "+ratpoison1.required+" drop");
		System.out.println();
		String ratPoisonType2="cholecalciferol";
		boolean strong2=false;
		int required2=2;
		RatPoison ratpoison2 = new RatPoison(ratPoisonType2,strong2,required2);
		System.out.println("Type of Rat Poison: "+ratpoison2.ratPoisonType);
		System.out.println("Strongness :"+ratpoison2.strong);
		System.out.println("Reqired: "+ratpoison2.required+" drop");
		System.out.println();
		String ratPoisonType3="zinc phosphide";
		boolean strong3=true;
		int required3=9;
		RatPoison ratpoison3 = new RatPoison(ratPoisonType3,strong3,required3);
		System.out.println("Type of Rat Possion: "+ratpoison3.ratPoisonType);
		System.out.println("Strongness :"+ratpoison3.strong);
		System.out.println("Reqired: "+ratpoison3.required+" drop");
		System.out.println();
		String ratPoisonType4="Arsenic";
		boolean strong4=true;
		int required4=5;
		RatPoison ratpoison4 = new RatPoison(ratPoisonType4,strong4,required4);
		System.out.println("Type of Rat Poison: "+ratpoison4.ratPoisonType);
		System.out.println("Strongness :"+ratpoison4.strong);
		System.out.println("Reqired: "+ratpoison4.required+" drop");
		System.out.println();
		String ratPoisonType5="Thallium";
		boolean strong5=false;
		int required5=7;
		RatPoison ratpoison5 = new RatPoison(ratPoisonType5,strong5,required5);
		System.out.println("Type of Rat Possion: "+ratpoison5.ratPoisonType);
		System.out.println("Strongness :"+ratpoison5.strong);
		System.out.println("Reqired: "+ratpoison5.required+" drop");
		System.out.println();
		System.out.println("List Of Anklet:");
		String material1="Siliver";
		int ankletprice1=2999;
		int kg1=500;
		Anklet anklet1 = new Anklet(material1,ankletprice1,kg1);
		System.out.println("Material Used: "+anklet1.material);
		System.out.println("Price for Anklet: "+anklet1.price);
		System.out.println("Weight :"+anklet1.kg);
		System.out.println();
		String material2="Gold";
		int ankletprice2=29999;
		int kg2=400;
		Anklet anklet2 = new Anklet(material2,ankletprice2,kg2);
		System.out.println("Material Used: "+anklet2.material);
		System.out.println("Price for Anklet: "+anklet2.price);
		System.out.println("Weight :"+anklet2.kg);
		System.out.println();
		String material3="Fiber";
		int ankletprice3=99;
		int kg3=50;
		Anklet anklet3 = new Anklet(material3,ankletprice3,kg3);
		System.out.println("Material Used: "+anklet3.material);
		System.out.println("Price for Anklet: "+anklet3.price);
		System.out.println("Weight :"+anklet3.kg);
		System.out.println();
		String material4="Gold";
		int ankletprice4=10000;
		int kg4=850;
		Anklet anklet4 = new Anklet(material4,ankletprice4,kg4);
		System.out.println("Material Used: "+anklet4.material);
		System.out.println("Price for Anklet: "+anklet4.price);
		System.out.println("Weight :"+anklet4.kg);
		System.out.println();
		String material5="Siliver";
		int ankletprice5=3999;
		int kg5=650;
		Anklet anklet5 = new Anklet(material5,ankletprice5,kg5);
		System.out.println("Material Used: "+anklet5.material);
		System.out.println("Price for Anklet: "+anklet5.price);
		System.out.println("Weight :"+anklet5.kg);
		System.out.println();
		System.out.println("List Of Magnate:");
		int magnetNumber1=10;
		String working1="Good";
		char grade1='A';
		Magnet magnet1 = new Magnet(magnetNumber1,working1,grade1);
		System.out.println("Number Of Magnet: "+magnet1.number);
		System.out.println("Working Of Magnet: "+magnet1.working);
		System.out.println("Grade Of Magnet: "+magnet1.grade);
		System.out.println();
		int magnetNumber2=05;
		String working2="Poor";
		char grade2='E';
		Magnet magnet2 = new Magnet(magnetNumber2,working2,grade2);
		System.out.println("Number Of Magnet: "+magnet2.number);
		System.out.println("Working Of Magnet: "+magnet2.working);
		System.out.println("Grade Of Magnet: "+magnet2.grade);
		System.out.println();
		int magnetNumber3=30;
		String working3="Very Good";
		char grade3='A';
		Magnet magnet3 = new Magnet(magnetNumber3,working3,grade3);
		System.out.println("Number Of Magnet: "+magnet3.number);
		System.out.println("Working Of Magnet: "+magnet3.working);
		System.out.println("Grade Of Magnet: "+magnet3.grade);
		System.out.println();
		int magnetNumber4=15;
		String working4="Execlent!";
		char grade4='A';
		Magnet magnet4 = new Magnet(magnetNumber4,working4,grade4);
		System.out.println("Number Of Magnet: "+magnet4.number);
		System.out.println("Working Of Magnet: "+magnet4.working);
		System.out.println("Grade Of Magnet: "+magnet4.grade);
		System.out.println();
		int magnetNumber5=01;
		String working5="Bad";
		char grade5='C';
		Magnet magnet5 = new Magnet(magnetNumber5,working5,grade5);
		System.out.println("Number Of Magnet: "+magnet5.number);
		System.out.println("Working Of Magnet: "+magnet5.working);
		System.out.println("Grade Of Magnet: "+magnet5.grade);
		System.out.println();
		System.out.println("The End");
		System.out.println("List Of Chain");
		System.out.println();
		String chainMaterial1="Gold";
		int chainWeight1=250;
		int chainPrice1=5500;
		Chain chain1 = new Chain(chainMaterial1,chainWeight1,chainPrice1);
		System.out.println("Chain Material: "+chain1.chainMaterial);
		System.out.println("Chain Weight: "+chain1.chainWeight);
		System.out.println("Chain Price: "+chain1.chainPrice);
		System.out.println();
		String chainMaterial2="Siliver";
		int chainWeight2=2500;
		int chainPrice2=500;
		Chain chain2 = new Chain(chainMaterial2,chainWeight2,chainPrice2);
		System.out.println("Chain Material: "+chain2.chainMaterial);
		System.out.println("Chain Weight: "+chain2.chainWeight);
		System.out.println("Chain Price: "+chain2.chainPrice);
		System.out.println();
		String chainMaterial3="Kari Mani";
		int chainWeight3=25;
		int chainPrice3=50;
		Chain chain3 = new Chain(chainMaterial3,chainWeight3,chainPrice3);
		System.out.println("Chain Material: "+chain3.chainMaterial);
		System.out.println("Chain Weight: "+chain3.chainWeight);
		System.out.println("Chain Price: "+chain3.chainPrice);
		System.out.println();
		String chainMaterial4="Dog Chain";
		int chainWeight4=200;
		int chainPrice4=250;
		Chain chain4 = new Chain(chainMaterial4,chainWeight4,chainPrice4);
		System.out.println("Chain Material: "+chain4.chainMaterial);
		System.out.println("Chain Weight: "+chain4.chainWeight);
		System.out.println("Chain Price: "+chain4.chainPrice);
		System.out.println();
		String chainMaterial5="Gold Chain";
		int chainWeight5=200;
		int chainPrice5=25000;
		Chain chain5 = new Chain(chainMaterial5,chainWeight5,chainPrice5);
		System.out.println("Chain Material: "+chain5.chainMaterial);
		System.out.println("Chain Weight: "+chain5.chainWeight);
		System.out.println("Chain Price: "+chain5.chainPrice);
		System.out.println();
		System.out.println("[Bar List]");
		System.out.println();
		String barName1="Lakshmi Wines";
		long contuctNumber1=9480028270l;
		String open1="Thirthahalli";
		Bar bar1 = new Bar(barName1,contuctNumber1,open1);
		System.out.println("Bar Name: "+bar1.barName);
		System.out.println("Contuct Number: "+bar1.contuctNumber);
		System.out.println("Address: "+bar1.open);
		System.out.println();
		String barName2="Ramkrishna Wines";
		long contuctNumber2=9480028270l;
		String open2="Thirthahalli";
		Bar bar2 = new Bar(barName2,contuctNumber2,open2);
		System.out.println("Bar Name: "+bar2.barName);
		System.out.println("Contuct Number: "+bar2.contuctNumber);
		System.out.println("Address: "+bar2.open);
		System.out.println();
		String barName3="Balaji Wines";
		long contuctNumber3=9480028270l;
		String open3="Thirthahalli";
		Bar bar3 = new Bar(barName3,contuctNumber3,open3);
		System.out.println("Bar Name: "+bar3.barName);
		System.out.println("Contuct Number: "+bar3.contuctNumber);
		System.out.println("Address: "+bar3.open);
		System.out.println();
		String barName4="Rock View";
		long contuctNumber4=9480028270l;
		String open4="Thirthahalli";
		Bar bar4 = new Bar(barName4,contuctNumber4,open4);
		System.out.println("Bar Name: "+bar4.barName);
		System.out.println("Contuct Number: "+bar4.contuctNumber);
		System.out.println("Address: "+bar4.open);
		System.out.println();
		String barName5="Durgamba Wines";
		long contuctNumber5=9480028270l;
		String open5="Thirthahalli";
		Bar bar5 = new Bar(barName5,contuctNumber5,open5);
		System.out.println("Bar Name: "+bar5.barName);
		System.out.println("Contuct Number: "+bar5.contuctNumber);
		System.out.println("Address: "+bar5.open);
		System.out.println();
		System.out.println("Sagar Eduction List");
		System.out.println();
		String eduction1="SSLC";
		int marks1=90;
		char sagarGrade1='A';
		Sagar sagar1 = new Sagar(eduction1,marks1,sagarGrade1);
		System.out.println("Sagar Eduction: "+sagar1.eduction);
		System.out.println("Sagar Marks: "+sagar1.marks);
		System.out.println("Sagar Grade: "+sagar1.grade);
		System.out.println();
		String eduction2="1st-PUC";
		int marks2=91;
		char sagarGrade2='A';
		Sagar sagar2 = new Sagar(eduction2,marks2,sagarGrade2);
		System.out.println("Sagar Eduction: "+sagar2.eduction);
		System.out.println("Sagar Marks: "+sagar2.marks);
		System.out.println("Sagar Grade: "+sagar2.grade);
		System.out.println();
		String eduction3="2nd-PUC";
		int marks3=95;
		char sagarGrade3='A';
		Sagar sagar3 = new Sagar(eduction3,marks3,sagarGrade3);
		System.out.println("Sagar Eduction: "+sagar3.eduction);
		System.out.println("Sagar Marks: "+sagar3.marks);
		System.out.println("Sagar Grade: "+sagar3.grade);
		System.out.println();
		String eduction4="BE";
		int marks4=9;
		char sagarGrade4='A';
		Sagar sagar4 = new Sagar(eduction4,marks4,sagarGrade4);
		System.out.println("Sagar Eduction: "+sagar4.eduction);
		System.out.println("Sagar Marks: "+sagar4.marks);
		System.out.println("Sagar Grade: "+sagar4.grade);
		System.out.println();
		String eduction5="MBA";
		int marks5=8;
		char sagarGrade5='B';
		Sagar sagar5 = new Sagar(eduction5,marks5,sagarGrade5);
		System.out.println("Sagar Eduction: "+sagar5.eduction);
		System.out.println("Sagar Marks: "+sagar5.marks);
		System.out.println("Sagar Grade: "+sagar5.grade);
		System.out.println();
		System.out.println("List Of Face:");
		System.out.println();
		String faceColour1="Black";
		int faceSize1=4;
		String faceShape1="Round";
		Face face1 = new Face(faceColour1,faceSize1,faceShape1);
		System.out.println("Face Colour: "+face1.colour);
		System.out.println("Face Size: "+face1.size);
		System.out.println("Face Shap: "+face1.shape);
		System.out.println();
		String faceColour2="White";
		int faceSize2=4;
		String faceShape2="Round";
		Face face2 = new Face(faceColour2,faceSize2,faceShape2);
		System.out.println("Face Colour: "+face2.colour);
		System.out.println("Face Size: "+face2.size);
		System.out.println("Face Shap: "+face2.shape);
		System.out.println();
		String faceColour3="Red";
		int faceSize3=7;
		String faceShape3="Ovel";
		Face face3 = new Face(faceColour3,faceSize3,faceShape3);
		System.out.println("Face Colour: "+face3.colour);
		System.out.println("Face Size: "+face3.size);
		System.out.println("Face Shap: "+face3.shape);
		System.out.println();
		String faceColour4="White";
		int faceSize4=4;
		String faceShape4="Round";
		Face face4 = new Face(faceColour4,faceSize4,faceShape4);
		System.out.println("Face Colour: "+face4.colour);
		System.out.println("Face Size: "+face4.size);
		System.out.println("Face Shap: "+face4.shape);
		System.out.println();
		String faceColour5="Black";
		int faceSize5=4;
		String faceShape5="Round";
		Face face5 = new Face(faceColour5,faceSize5,faceShape5);
		System.out.println("Face Colour: "+face5.colour);
		System.out.println("Face Size: "+face5.size);
		System.out.println("Face Shap: "+face5.shape);
		System.out.println();
		System.out.println("|||||END|||||");		
	}
}